steps:
  # Build and push the Docker image using Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=packages/twenty-server/Dockerfile.production'
      - '--context=dir:///workspace'
      - '--destination=gcr.io/$PROJECT_ID/top-backend:latest'
      - '--cache=true'
      - '--cache-ttl=1h'
      - '--no-push-cache'  # Don't use cache for this build to force rebuild

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'top-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/top-backend:latest'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--add-cloudsql-instances=tracepoint-d4c9d:us-east1:tracepoint-top-db'
      - '--set-env-vars=DATABASE_MIGRATION=run,SERVER_URL=https://top.tracepointops.com,FRONTEND_URL=https://top.tracepointops.com,IS_MULTIWORKSPACE_ENABLED=false,DEFAULT_SUBDOMAIN=,APP_SECRET=7jogTOTb2QRaGyesfmDJ4fG+mz/wYywEpzPiGHSTIwU=,REDIS_URL=redis://default:AXgtAAIncDIzZGMxY2FiZjBlZWU0OWYxOGE1OTAxYWIxZmI5MTdiNnAyMzA3NjU@glowing-gelding-30765.upstash.io:6379,PG_DATABASE_URL=postgres://postgres:testpassword@localhost:5432/postgres'
      - '--timeout=600'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=0'

images:
  - 'gcr.io/$PROJECT_ID/top-backend:latest'

timeout: 3600s
